export enum EventType {
  PubVisit = 'pub_visit',
  ChurchVisit = 'church_visit',
  WorkplaceIncident = 'workplace_incident',
  RelationshipFormed = 'relationship_formed',
  RelationshipChanged = 'relationship_changed',
  NeedsCrisis = 'needs_crisis',
  CitizenBorn = 'citizen_born',
  CitizenDied = 'citizen_died',
  CitizenMigrated = 'citizen_migrated',
  BusinessOpened = 'business_opened',
  BusinessClosed = 'business_closed',
  BusinessSold = 'business_sold',
  Promotion = 'promotion',
  UnemploymentSpike = 'unemployment_spike',
  Strike = 'strike',
  ElectionHeld = 'election',
  PolicyPassed = 'policy_passed',
  FactionFormed = 'faction_formed',
  CorruptionAllegation = 'corruption_allegation',
  BuildingConstructed = 'building_constructed',
  BuildingDemolished = 'building_demolished',
  DistrictEvolved = 'district_evolved',
  YearClosed = 'year_closed',
  CitizenGraduated = 'citizen_graduated',
}
